mode: auto
avatar:
  url: /images/avatar.jpg # ä½ çš„å¤´åƒå›¾ç‰‡åœ°å€
  rounded: true
  opacity: 1
banner:
  enable: true
  title: 
    - æ‘¸
    - ğŸŸ
    - äºº
    - çš„
    - æ—¥
    - å¸¸
  border: true
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: ri:arrow-down-s-line
katex:
  copy_tex: true
  global: false
  options: {}
reward:
  enable: false
head:
  css:
    online_fonts: https://fonts.googleapis.com/css2?family=Noto+Serif+SC:wght@900&display=swap
    public_fonts: /fonts/fonts.css
say:
  enable: false
mourn:
  enable: true
  days:
    - 12-13
post_meta:
  item_text: false
  created_at: true
  updated_at: true
  categories: true
  tags: true